---
- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Modify /etc/hosts
  template:
    src=../templates/hosts.j2
    dest=/etc/hosts

- name: Install necessary packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - gnupg2
    - net-tools

- name: Install containerd, WasmEdge and crun
  script: ../scripts/install_cr.sh
  args:
    creates: /etc/containerd/config.toml

- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Add an apt signing key for Kubernetes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Adding apt repository for Kubernetes
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list

- name: Install Kubernetes binaries
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - kubelet={{ k8s_version }}-00
      - kubeadm={{ k8s_version }}-00
      - kubectl={{ k8s_version }}-00

- name: Configure containerd
  blockinfile:
    create: true
    path: /etc/modules-load.d/containerd.conf
    block: |
      overlay
      br_netfilter

- name: Configure containerd
  shell: |
    sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml

- name: Restart containerd
  service:
    name: containerd
    state: restarted
    enabled: yes

- name: Enable kernel modules
  shell: |
    modprobe overlay
    modprobe br_netfilter

- name: Configure IP forwarding and iptables
  blockinfile:
    create: true
    path: /etc/sysctl.conf
    block: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1

- name: Persist changes
  command: sysctl -p

- name: Configure kubelet
  lineinfile:
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    line: Environment="KUBELET_EXTRA_ARGS=--node-ip={{ ansible_host }}"
