---
- name: Initialize the Kubernetes cluster using kubeadm
  command: >
    kubeadm init
    --apiserver-advertise-address="{{ ansible_host }}"
    --apiserver-cert-extra-sans="{{ ansible_host }}"
    --pod-network-cidr=172.16.0.0/16
    --cri-socket=/var/run/containerd/containerd.sock

- name: Create kube directory
  file:
    path: /home/{{ ansible_user }}/.kube
    state: directory

- name: Setup kubeconfig for user
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ ansible_user }}/.kube/config
    remote_src: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Download calico.conf
  get_url:
    url: https://docs.projectcalico.org/v3.20/manifests/calico.yaml
    dest: /home/{{ ansible_user }}/calico.yaml

- name: Add pod config to calico.yaml
  lineinfile:
    dest: /home/{{ ansible_user }}/calico.yaml
    regexp: '^\s{12}#\s*- name: CALICO_IPV4POOL_CIDR.*$'
    line: '            - name: CALICO_IPV4POOL_CIDR'

- name: Add pod config to calico.yaml
  lineinfile:
    dest: /home/{{ ansible_user }}/calico.yaml
    regexp: '^\s{12}#\s*  value: "192.168.0.0\/16".*$'
    line: '              value: "172.16.0.0/16"'

- name: Install calico CNI
  become: false
  command: kubectl create -f calico.yaml

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  become: false
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
